CREATE TABLE "user" (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
email VARCHAR(255),
is_verified BOOLEAN NOT NULL,
lvl INTEGER NOT NULL
);

CREATE TABLE "stat" (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
wrong_answers INTEGER NOT NULL,
correct_answers INTEGER NOT NULL,
total_questions INTEGER NOT NULL,
user_id BIGINT, CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE
);

